### ISSUE TITLE
Two consecutive updates

### ISSUE THREAD

**Issue by sadortun** [repman-io/composer-plugin#5]
Hi @akondas 

Thanks for your awesome project ! 

After some head scratching, i think there is an issue with the plugin.

When performing a `composer update` with no `vendor/` folder, all packages have the `mirrors` proprety set in the `.lock` file.

But, when running a second `composer update` all the `mirrors` get removed.

![image](https://user-images.githubusercontent.com/794449/79941821-3411c600-8433-11ea-84ff-c0e3f7ac9ecb.png)

Have a good day,
Samuel

**Comment by akondas** [comment]
Hi @sadortun, thanks for feedback.
Actually, this behavior can be observed, but this should not affect the installation of packages. This is because the plugin integrates in the process of installing or updating the package. If there is nothing to install or update then mirrors are not added.

One could change this behavior so that adding a mirror will always work for each package, but I would have to test if such a change would cause other problems.

**Comment by akondas** [comment]
Other solution is to use the configuration in the `composer.json` file:
```json
{
  "repositories": [
    {"type": "composer", "url": "https://repo.repman.io"},
    {"packagist": false}
  ]
}
```
Well, then the plugin becomes unnecessary :wink:
